/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline;

import javax.swing.JButton;

/**
 *
 * @author oalhi
 */
public class AdminProfile extends javax.swing.JFrame {

    /**
     * Creates new form AdminProfile
     */
    public AdminProfile() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addstaffButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddStaffmember = new javax.swing.JPanel();
        SName = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        Smail = new javax.swing.JTextField();
        tele = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        BanUser = new javax.swing.JPanel();
        Banmail = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        SaveButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        EButton = new javax.swing.JButton();
        SoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BanUsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        addstaffButton.setBorderPainted(false);
        addstaffButton.setContentAreaFilled(false);
        addstaffButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstaffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addstaffButton);
        addstaffButton.setBounds(180, 150, 100, 40);

        jLabel5.setForeground(new java.awt.Color(0, 98, 206));
        jLabel5.setText("Add Staffmember....");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 150, 110, 40);

        jLabel13.setForeground(new java.awt.Color(0, 98, 206));
        jLabel13.setText("Ban User....");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(180, 210, 110, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 40, 280, 40);

        AddStaffmember.setBackground(new java.awt.Color(255, 255, 255));
        AddStaffmember.setLayout(null);
        AddStaffmember.add(SName);
        SName.setBounds(20, 40, 130, 30);
        AddStaffmember.add(address);
        address.setBounds(170, 40, 130, 30);
        AddStaffmember.add(Smail);
        Smail.setBounds(20, 100, 130, 30);
        AddStaffmember.add(tele);
        tele.setBounds(170, 100, 130, 30);
        AddStaffmember.add(Age);
        Age.setBounds(20, 160, 130, 30);

        jLabel15.setText("Address:");
        AddStaffmember.add(jLabel15);
        jLabel15.setBounds(170, 20, 70, 14);

        jLabel16.setText("Email:");
        AddStaffmember.add(jLabel16);
        jLabel16.setBounds(20, 80, 80, 14);

        jLabel17.setText("Telephone:");
        AddStaffmember.add(jLabel17);
        jLabel17.setBounds(170, 80, 90, 14);

        jLabel18.setText("Password:");
        AddStaffmember.add(jLabel18);
        jLabel18.setBounds(170, 140, 70, 14);

        jLabel19.setText("Name:");
        AddStaffmember.add(jLabel19);
        jLabel19.setBounds(20, 20, 60, 14);

        jLabel21.setText("Age:");
        AddStaffmember.add(jLabel21);
        jLabel21.setBounds(20, 140, 70, 14);

        SaveButton.setBorderPainted(false);
        SaveButton.setContentAreaFilled(false);
        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        AddStaffmember.add(SaveButton);
        SaveButton.setBounds(240, 210, 80, 40);

        jLabel20.setBackground(new java.awt.Color(0, 98, 206));
        jLabel20.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Save");
        jLabel20.setOpaque(true);
        AddStaffmember.add(jLabel20);
        jLabel20.setBounds(240, 210, 80, 40);
        AddStaffmember.add(pass);
        pass.setBounds(170, 160, 130, 30);

        getContentPane().add(AddStaffmember);
        AddStaffmember.setBounds(300, 120, 330, 250);

        BanUser.setBackground(new java.awt.Color(255, 255, 255));
        BanUser.setLayout(null);
        BanUser.add(Banmail);
        Banmail.setBounds(30, 60, 260, 30);

        jLabel23.setText("Email:");
        BanUser.add(jLabel23);
        jLabel23.setBounds(30, 40, 80, 14);

        SaveButton1.setBorderPainted(false);
        SaveButton1.setContentAreaFilled(false);
        SaveButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton1ActionPerformed(evt);
            }
        });
        BanUser.add(SaveButton1);
        SaveButton1.setBounds(240, 210, 80, 40);

        jLabel28.setBackground(new java.awt.Color(0, 98, 206));
        jLabel28.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Ban");
        jLabel28.setOpaque(true);
        BanUser.add(jLabel28);
        jLabel28.setBounds(240, 210, 80, 40);

        getContentPane().add(BanUser);
        BanUser.setBounds(300, 120, 330, 250);

        EButton.setBorderPainted(false);
        EButton.setContentAreaFilled(false);
        EButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EButton);
        EButton.setBounds(720, 0, 30, 30);

        SoButton.setBorderPainted(false);
        SoButton.setContentAreaFilled(false);
        SoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SoButton);
        SoButton.setBounds(640, 330, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/ClientProfile.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 751, 383);

        BanUsButton.setBorderPainted(false);
        BanUsButton.setContentAreaFilled(false);
        BanUsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BanUsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanUsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BanUsButton);
        BanUsButton.setBounds(180, 210, 100, 40);

        setSize(new java.awt.Dimension(751, 383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public JButton getaddStaffButton()
    {
        return  addstaffButton;
    }
    public JButton getsaButton()
    {
        return  SaveButton;
    }
    public JButton getsaButton1()
    {
        return  SaveButton1;
    }
    public JButton getsoButton()
    {
        return  SoButton;
    }
    public JButton geteButton()
    {
        return  EButton;
    }
    public JButton getBanButton()
    {
        return  BanUsButton;
    }
    public String getnpass()
    {
        return pass.getText();
    }
    public String getname()
    {
        return SName.getText();
    }
    public String getaddress()
    {
        return address.getText();
    }
    public String getmail()
    {
        return Smail.getText();
    }
    public String gettele()
    {
        return tele.getText();
    }
    public String getage()
    {
        return Age.getText();
    }

    public String getbmail()
    {
        return Banmail.getText();
    }
 
    public void setbm(String x)
    {
         Banmail.setText(x);
    }
    public void setDa(String x)
    {
         pass.setText(x);
         SName.setText(x);
         address.setText(x);
         Smail.setText(x);
         tele.setText(x);
         Age.setText(x);
    }
    
    
    
    
    
    
    
    
    
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed

    }//GEN-LAST:event_SaveButtonActionPerformed

    private void addstaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstaffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addstaffButtonActionPerformed

    private void EButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EButtonActionPerformed

    private void SoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoButtonActionPerformed

    private void BanUsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanUsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BanUsButtonActionPerformed

    private void SaveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel AddStaffmember;
    private javax.swing.JTextField Age;
    private javax.swing.JButton BanUsButton;
    public javax.swing.JPanel BanUser;
    private javax.swing.JTextField Banmail;
    private javax.swing.JButton EButton;
    private javax.swing.JTextField SName;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SaveButton1;
    private javax.swing.JTextField Smail;
    private javax.swing.JButton SoButton;
    private javax.swing.JTextField address;
    private javax.swing.JButton addstaffButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField tele;
    // End of variables declaration//GEN-END:variables
}
