/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline;

import javax.swing.JButton;

/**
 *
 * @author oalhi
 */
public class ClientProfile extends javax.swing.JFrame {

    /**
     * Creates new form ClientProfile
     */
    public ClientProfile() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NButton = new javax.swing.JButton();
        NotificationIcon = new javax.swing.JLabel();
        NotificationPanel = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        Notify = new javax.swing.JTextArea();
        EButton = new javax.swing.JButton();
        SoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PasswordChange = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        newpass = new javax.swing.JPasswordField();
        SaButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        updateP = new javax.swing.JButton();
        ReservButt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        NButton.setBorderPainted(false);
        NButton.setContentAreaFilled(false);
        NButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NButton);
        NButton.setBounds(640, 30, 60, 60);

        NotificationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/Nofify1.jpg"))); // NOI18N
        getContentPane().add(NotificationIcon);
        NotificationIcon.setBounds(630, 30, 80, 60);

        NotificationPanel.setLayout(null);
        NotificationPanel.add(jScrollBar1);
        jScrollBar1.setBounds(180, 20, 17, 200);

        Notify.setColumns(20);
        Notify.setRows(5);
        jScrollPane1.setViewportView(Notify);

        NotificationPanel.add(jScrollPane1);
        jScrollPane1.setBounds(0, 10, 200, 220);

        getContentPane().add(NotificationPanel);
        NotificationPanel.setBounds(430, 20, 200, 240);

        EButton.setBorderPainted(false);
        EButton.setContentAreaFilled(false);
        EButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EButton);
        EButton.setBounds(720, 0, 30, 30);

        SoButton.setBorderPainted(false);
        SoButton.setContentAreaFilled(false);
        SoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SoButton);
        SoButton.setBounds(640, 330, 100, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 40, 280, 40);

        PasswordChange.setBackground(new java.awt.Color(255, 255, 255));
        PasswordChange.setLayout(null);

        jLabel6.setText("New Password:");
        PasswordChange.add(jLabel6);
        jLabel6.setBounds(20, 50, 110, 40);
        PasswordChange.add(newpass);
        newpass.setBounds(130, 60, 150, 30);

        SaButton1.setBorderPainted(false);
        SaButton1.setContentAreaFilled(false);
        SaButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaButton1ActionPerformed(evt);
            }
        });
        PasswordChange.add(SaButton1);
        SaButton1.setBounds(240, 210, 80, 40);

        jLabel7.setBackground(new java.awt.Color(0, 98, 206));
        jLabel7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Save");
        jLabel7.setOpaque(true);
        PasswordChange.add(jLabel7);
        jLabel7.setBounds(240, 210, 80, 40);

        getContentPane().add(PasswordChange);
        PasswordChange.setBounds(300, 120, 330, 250);

        updateP.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        updateP.setForeground(new java.awt.Color(0, 98, 206));
        updateP.setText("Update Password....");
        updateP.setBorderPainted(false);
        updateP.setContentAreaFilled(false);
        updateP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(updateP);
        updateP.setBounds(170, 130, 130, 40);

        ReservButt.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        ReservButt.setForeground(new java.awt.Color(0, 98, 206));
        ReservButt.setText("Reservations....");
        ReservButt.setBorderPainted(false);
        ReservButt.setContentAreaFilled(false);
        ReservButt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(ReservButt);
        ReservButt.setBounds(170, 170, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/ClientProfile.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 751, 383);

        setSize(new java.awt.Dimension(751, 383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getupdatePasButton()
    {
        return  updateP;
    }
    public JButton getsoButton()
    {
        return  SoButton;
    }
    public JButton getrsButton()
    {
        return  ReservButt;
    }
    public JButton getNButton()
    {
        return  NButton;
    }
    public JButton getEButton()
    {
        return  EButton;
    }
    public JButton getsave1Button()
    {
        return  SaButton1;
    }


    public JButton getresrvButton()
    {
        return  ReservButt;
    }
    public String getnpass()
    {
        return newpass.getText();
    }


    public void UpdatePanel(String x)
    {
         Notify.append(x);
    }
 
    public void setnpass(String x)
    {
         newpass.setText(x);
    }
    
    
    
    
    
    
    
    
    private void SoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoButtonActionPerformed

    }//GEN-LAST:event_SoButtonActionPerformed

    private void EButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonActionPerformed
        
    }//GEN-LAST:event_EButtonActionPerformed

    private void SaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaButton1ActionPerformed

    private void NButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EButton;
    private javax.swing.JButton NButton;
    private javax.swing.JLabel NotificationIcon;
    public javax.swing.JPanel NotificationPanel;
    public javax.swing.JTextArea Notify;
    public javax.swing.JPanel PasswordChange;
    private javax.swing.JButton ReservButt;
    private javax.swing.JButton SaButton1;
    private javax.swing.JButton SoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField newpass;
    public javax.swing.JButton updateP;
    // End of variables declaration//GEN-END:variables
}
