/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline;

import javax.swing.JButton;

/**
 *
 * @author oalhi
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUp = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        EButton = new javax.swing.JButton();
        LButton = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        Admin = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        SignUp.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        SignUp.setForeground(new java.awt.Color(153, 153, 153));
        SignUp.setText("Create new user account ? Sign up ");
        SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(SignUp);
        SignUp.setBounds(460, 340, 190, 15);
        getContentPane().add(mail);
        mail.setBounds(390, 130, 320, 40);

        EButton.setBorderPainted(false);
        EButton.setContentAreaFilled(false);
        EButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(EButton);
        EButton.setBounds(717, 0, 30, 30);

        LButton.setBorderPainted(false);
        LButton.setContentAreaFilled(false);
        LButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(LButton);
        LButton.setBounds(493, 293, 110, 40);
        getContentPane().add(password);
        password.setBounds(390, 230, 320, 40);

        Admin.setText("Admin");
        Admin.setOpaque(false);
        getContentPane().add(Admin);
        Admin.setBounds(670, 280, 81, 23);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/Login.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 751, 383);

        setSize(new java.awt.Dimension(751, 383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getLoginButton()
    {
        return LButton;
    }
    public JButton getExitButton()
    {
        return EButton;
    }
    public String getmail()
    {
        return mail.getText();
    }
    
    public String getpassword()
    {
        return password.getText();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox Admin;
    private javax.swing.JButton EButton;
    private javax.swing.JButton LButton;
    private javax.swing.JLabel SignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField mail;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
