/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline;

/**
 *
 * @author oalhi
 */
public class Staffmember extends javax.swing.JFrame {

    /**
     * Creates new form Staffmember
     */
    public Staffmember() {
        initComponents();
           ProfileUpdate.setVisible(false);
        PasswordChange.setVisible(false);
        AddFlight.setVisible(false);
        RemoveFlight.setVisible(false);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PasswordChange = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        SavePasswordChange = new javax.swing.JLabel();
        ProfileUpdate = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SaveProfileUpdate = new javax.swing.JLabel();
        AddFlight = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        SaveAddFlight = new javax.swing.JLabel();
        RemoveFlight = new javax.swing.JPanel();
        FlightNumbertext = new javax.swing.JTextField();
        FlightNumberLabel = new javax.swing.JLabel();
        SaveRemoveFlight = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Reservations = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 0, 30, 30);

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 330, 100, 40);

        PasswordChange.setBackground(new java.awt.Color(255, 255, 255));
        PasswordChange.setLayout(null);

        jLabel6.setText("New Password:");
        PasswordChange.add(jLabel6);
        jLabel6.setBounds(20, 50, 110, 40);
        PasswordChange.add(jPasswordField1);
        jPasswordField1.setBounds(130, 60, 150, 30);

        SavePasswordChange.setBackground(new java.awt.Color(0, 98, 206));
        SavePasswordChange.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        SavePasswordChange.setForeground(new java.awt.Color(255, 255, 255));
        SavePasswordChange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SavePasswordChange.setText("Save");
        SavePasswordChange.setOpaque(true);
        PasswordChange.add(SavePasswordChange);
        SavePasswordChange.setBounds(240, 210, 80, 40);

        getContentPane().add(PasswordChange);
        PasswordChange.setBounds(300, 120, 330, 250);

        ProfileUpdate.setBackground(new java.awt.Color(255, 255, 255));
        ProfileUpdate.setLayout(null);
        ProfileUpdate.add(jTextField1);
        jTextField1.setBounds(20, 50, 130, 30);
        ProfileUpdate.add(jTextField2);
        jTextField2.setBounds(170, 50, 130, 30);
        ProfileUpdate.add(jTextField3);
        jTextField3.setBounds(20, 120, 130, 30);
        ProfileUpdate.add(jTextField4);
        jTextField4.setBounds(170, 120, 130, 30);
        ProfileUpdate.add(jTextField5);
        jTextField5.setBounds(20, 200, 130, 30);

        jLabel8.setText("Address:");
        ProfileUpdate.add(jLabel8);
        jLabel8.setBounds(170, 30, 70, 14);

        jLabel9.setText("Email:");
        ProfileUpdate.add(jLabel9);
        jLabel9.setBounds(20, 100, 80, 14);

        jLabel10.setText("Telephone:");
        ProfileUpdate.add(jLabel10);
        jLabel10.setBounds(170, 100, 90, 14);

        jLabel11.setText("Age:");
        ProfileUpdate.add(jLabel11);
        jLabel11.setBounds(20, 180, 70, 14);

        jLabel14.setText("Name:");
        ProfileUpdate.add(jLabel14);
        jLabel14.setBounds(20, 30, 60, 14);

        SaveProfileUpdate.setBackground(new java.awt.Color(0, 98, 206));
        SaveProfileUpdate.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        SaveProfileUpdate.setForeground(new java.awt.Color(255, 255, 255));
        SaveProfileUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SaveProfileUpdate.setText("Save");
        SaveProfileUpdate.setOpaque(true);
        SaveProfileUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveProfileUpdateMouseClicked(evt);
            }
        });
        ProfileUpdate.add(SaveProfileUpdate);
        SaveProfileUpdate.setBounds(240, 210, 80, 40);

        getContentPane().add(ProfileUpdate);
        ProfileUpdate.setBounds(300, 120, 330, 250);

        AddFlight.setBackground(new java.awt.Color(255, 255, 255));
        AddFlight.setLayout(null);
        AddFlight.add(jTextField6);
        jTextField6.setBounds(20, 40, 130, 30);
        AddFlight.add(jTextField7);
        jTextField7.setBounds(170, 40, 130, 30);
        AddFlight.add(jTextField8);
        jTextField8.setBounds(20, 100, 130, 30);

        jLabel15.setText("Number of Seats:");
        AddFlight.add(jLabel15);
        jLabel15.setBounds(170, 20, 130, 14);

        jLabel16.setText("Airline:");
        AddFlight.add(jLabel16);
        jLabel16.setBounds(20, 80, 100, 14);

        jLabel19.setText("Flight Number:");
        AddFlight.add(jLabel19);
        jLabel19.setBounds(20, 20, 120, 14);

        SaveAddFlight.setBackground(new java.awt.Color(0, 98, 206));
        SaveAddFlight.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        SaveAddFlight.setForeground(new java.awt.Color(255, 255, 255));
        SaveAddFlight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SaveAddFlight.setText("Save");
        SaveAddFlight.setOpaque(true);
        AddFlight.add(SaveAddFlight);
        SaveAddFlight.setBounds(240, 210, 80, 40);

        getContentPane().add(AddFlight);
        AddFlight.setBounds(300, 120, 330, 250);

        RemoveFlight.setBackground(new java.awt.Color(255, 255, 255));
        RemoveFlight.setLayout(null);
        RemoveFlight.add(FlightNumbertext);
        FlightNumbertext.setBounds(30, 60, 260, 30);

        FlightNumberLabel.setText("Flight Number:");
        RemoveFlight.add(FlightNumberLabel);
        FlightNumberLabel.setBounds(30, 40, 130, 14);

        SaveRemoveFlight.setBackground(new java.awt.Color(0, 98, 206));
        SaveRemoveFlight.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        SaveRemoveFlight.setForeground(new java.awt.Color(255, 255, 255));
        SaveRemoveFlight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SaveRemoveFlight.setText("Remove");
        SaveRemoveFlight.setOpaque(true);
        RemoveFlight.add(SaveRemoveFlight);
        SaveRemoveFlight.setBounds(240, 210, 80, 40);

        getContentPane().add(RemoveFlight);
        RemoveFlight.setBounds(300, 120, 330, 250);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 40, 280, 40);

        jLabel3.setForeground(new java.awt.Color(0, 98, 206));
        jLabel3.setText("Update Password....");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 130, 110, 40);

        jLabel4.setForeground(new java.awt.Color(0, 98, 206));
        jLabel4.setText("Update Profile....");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 170, 110, 40);

        jLabel5.setForeground(new java.awt.Color(0, 98, 206));
        jLabel5.setText("Add Flight....");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 210, 110, 40);

        jLabel13.setForeground(new java.awt.Color(0, 98, 206));
        jLabel13.setText("Remove Flight....");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(190, 250, 110, 40);

        Reservations.setForeground(new java.awt.Color(0, 98, 206));
        Reservations.setText("Reservations....");
        Reservations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reservations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservationsMouseClicked(evt);
            }
        });
        getContentPane().add(Reservations);
        Reservations.setBounds(190, 290, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/ClientProfile.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 751, 383);

        setSize(new java.awt.Dimension(751, 383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginGUI L = new LoginGUI();
        L.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SaveProfileUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveProfileUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveProfileUpdateMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        ProfileUpdate.setVisible(false);
        PasswordChange.setVisible(true);
        AddFlight.setVisible(false);
        RemoveFlight.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        ProfileUpdate.setVisible(true);
        PasswordChange.setVisible(false);
        AddFlight.setVisible(false);
        RemoveFlight.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        ProfileUpdate.setVisible(false);
        PasswordChange.setVisible(false);
        AddFlight.setVisible(true);
        RemoveFlight.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        ProfileUpdate.setVisible(false);
        PasswordChange.setVisible(false);
        AddFlight.setVisible(false);
        RemoveFlight.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void ReservationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationsMouseClicked
        ReservationMenu R = new ReservationMenu();
        R.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReservationsMouseClicked

    /**
     * @param args the command line arguments
     */

   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staffmember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddFlight;
    private javax.swing.JLabel FlightNumberLabel;
    private javax.swing.JTextField FlightNumbertext;
    private javax.swing.JPanel PasswordChange;
    private javax.swing.JPanel ProfileUpdate;
    private javax.swing.JPanel RemoveFlight;
    private javax.swing.JLabel Reservations;
    private javax.swing.JLabel SaveAddFlight;
    private javax.swing.JLabel SavePasswordChange;
    private javax.swing.JLabel SaveProfileUpdate;
    private javax.swing.JLabel SaveRemoveFlight;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
